"""
PatentScout — Similarity Calibration Script

Loads the sentence-transformers model and scores a set of canonical
(feature, claim element) pairs to calibrate threshold settings.

Usage:
    cd /path/to/PatentScout
    python scripts/calibrate_similarity.py

Output:
    Prints a score table to stdout.
    Saves results to examples/similarity_calibration.json.
"""

from __future__ import annotations

import json
import os
import sys
import time

# Make project root importable
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

from dotenv import load_dotenv
load_dotenv()

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

from config import settings


# ---------------------------------------------------------------------------
# Canonical calibration pairs
# ---------------------------------------------------------------------------
# Each entry: (feature_description, claim_element, expected_level)
# expected_level: "HIGH" | "MODERATE" | "LOW" | "NONE"

CALIBRATION_PAIRS = [
    # ── HIGH expected ──────────────────────────────────────────────────────
    (
        "A portable solar panel that folds into a compact case and charges mobile phones via USB-C",
        "a foldable photovoltaic panel assembly configured to charge a portable electronic device via a USB connector",
        "HIGH",
    ),
    (
        "integrated battery pack for storing solar energy",
        "a rechargeable battery unit disposed within the housing, wherein the battery unit stores electrical energy generated by the photovoltaic cells",
        "HIGH",
    ),
    (
        "solar panel folds into compact case",
        "a portable solar charging device comprising a foldable panel pivotally connected to a housing",
        "HIGH",
    ),

    # ── MODERATE expected ──────────────────────────────────────────────────
    (
        "USB-C charging port for mobile phones",
        "an output connector comprising a Universal Serial Bus interface configured to supply power to an external device",
        "MODERATE",
    ),
    (
        "energy storage when sunlight is not available",
        "a power storage module operably coupled to the solar cells for storing harvested energy during periods of reduced solar irradiance",
        "MODERATE",
    ),
    (
        "portable foldable solar charger",
        "a photovoltaic module comprising at least two rigid solar panels connected by a hinge mechanism",
        "MODERATE",
    ),

    # ── LOW / NONE expected ────────────────────────────────────────────────
    (
        "A portable solar panel battery charger",
        "a method of processing image data comprising receiving a digital image, applying a convolutional filter, and outputting a feature map",
        "NONE",
    ),
    (
        "USB-C solar charging port",
        "a database indexing method comprising creating a B-tree index on a column of a relational database",
        "NONE",
    ),
    (
        "foldable solar panel for mobile charging",
        "a pharmaceutical compound comprising a benzene ring substituted at the para position with a hydroxyl group",
        "NONE",
    ),
]

# Patent-language reformulations for the first few pairs (simulates what Gemini produces)
PATENT_LANGUAGE_REFORMULATIONS = [
    "a portable photovoltaic charging device comprising a foldable solar panel assembly and a USB-C output port configured to charge mobile electronic devices",
    "a rechargeable energy storage unit comprising a battery pack disposed within the housing, wherein the battery pack is configured to store photovoltaic energy",
    "a compact portable device comprising a foldable solar panel configured to pivot between a collapsed storage position and an expanded charging position",
    "a Universal Serial Bus Type-C charging interface disposed on the housing, configured to supply electrical power to a connected mobile device",
    "an energy storage module operably coupled to the photovoltaic cells, configured to store electrical energy during periods of insufficient solar irradiance",
    "a portable solar power bank comprising a foldable photovoltaic panel array connected to the housing by a hinge mechanism",
    "a portable solar panel battery charger",   # no improvement for non-patent pairs
    "a USB-C solar charging port",
    "a foldable solar panel for mobile charging",
]


def _level(score: float) -> str:
    if score >= settings.SIMILARITY_THRESHOLD_HIGH:
        return "HIGH"
    if score >= settings.SIMILARITY_THRESHOLD_MODERATE:
        return "MODERATE"
    if score >= settings.SIMILARITY_THRESHOLD_LOW:
        return "LOW"
    return "NONE"


def main() -> None:
    print(f"\n{'=' * 72}")
    print("  PatentScout — Similarity Calibration")
    print(f"{'=' * 72}")
    print(f"  Model : {settings.EMBEDDING_MODEL_NAME}")
    print(f"  Thresholds: HIGH≥{settings.SIMILARITY_THRESHOLD_HIGH}  "
          f"MOD≥{settings.SIMILARITY_THRESHOLD_MODERATE}  "
          f"LOW≥{settings.SIMILARITY_THRESHOLD_LOW}")
    print()

    # Load model
    t0 = time.time()
    print("Loading model...")
    try:
        model = SentenceTransformer(settings.EMBEDDING_MODEL_NAME)
        model_name = settings.EMBEDDING_MODEL_NAME
    except Exception as exc:
        print(f"  Primary model failed: {exc}")
        print(f"  Trying fallback: {settings.EMBEDDING_MODEL_FALLBACK_NAME}")
        model = SentenceTransformer(settings.EMBEDDING_MODEL_FALLBACK_NAME)
        model_name = settings.EMBEDDING_MODEL_FALLBACK_NAME
    print(f"  Model loaded: {model_name} ({time.time() - t0:.2f}s)\n")

    results = []
    correct = 0
    total = len(CALIBRATION_PAIRS)

    header = (
        f"{'#':>2}  {'Expected':>8}  {'Orig':>6}  {'Patent':>6}  {'Max':>6}  "
        f"{'Level':>8}  {'Match?':>6}  Feature (truncated)"
    )
    print(header)
    print("-" * 110)

    for i, (feat, claim, expected) in enumerate(CALIBRATION_PAIRS):
        patent_text = PATENT_LANGUAGE_REFORMULATIONS[i] if i < len(PATENT_LANGUAGE_REFORMULATIONS) else feat

        emp_feat  = model.encode([feat])
        emp_pat   = model.encode([patent_text])
        emp_claim = model.encode([claim])

        sim_orig   = float(cosine_similarity(emp_feat, emp_claim)[0][0])
        sim_patent = float(cosine_similarity(emp_pat, emp_claim)[0][0])
        sim_max    = max(sim_orig, sim_patent)

        level = _level(sim_max)
        # A "match" is when level >= expected or both are NONE
        match = (
            level == expected
            or (level in ("HIGH", "MODERATE") and expected in ("HIGH", "MODERATE"))
        )
        if match:
            correct += 1

        row = {
            "pair_index": i + 1,
            "feature": feat,
            "patent_language": patent_text,
            "claim_element": claim,
            "expected_level": expected,
            "sim_original": round(sim_orig, 4),
            "sim_patent_language": round(sim_patent, 4),
            "sim_max": round(sim_max, 4),
            "computed_level": level,
            "correct": match,
        }
        results.append(row)

        match_sym = "✓" if match else "✗"
        print(
            f"{i+1:>2}  {expected:>8}  {sim_orig:>6.3f}  {sim_patent:>6.3f}  "
            f"{sim_max:>6.3f}  {level:>8}  {match_sym:>6}  {feat[:50]}"
        )

    print("-" * 110)
    print(f"\n  Accuracy: {correct}/{total} pairs correctly classified ({100*correct/total:.0f}%)")
    print(f"\n  Threshold recommendations based on calibration pairs:")
    high_scores = [r["sim_max"] for r in results if r["expected_level"] == "HIGH"]
    mod_scores  = [r["sim_max"] for r in results if r["expected_level"] == "MODERATE"]
    none_scores = [r["sim_max"] for r in results if r["expected_level"] == "NONE"]

    if high_scores:
        print(f"    HIGH pairs avg sim_max:     {np.mean(high_scores):.3f} (min={min(high_scores):.3f})")
    if mod_scores:
        print(f"    MODERATE pairs avg sim_max: {np.mean(mod_scores):.3f} (min={min(mod_scores):.3f})")
    if none_scores:
        print(f"    NONE pairs avg sim_max:     {np.mean(none_scores):.3f} (max={max(none_scores):.3f})")

    # Suggest thresholds
    if high_scores and mod_scores and none_scores:
        suggested_high = round((min(high_scores) + max(mod_scores)) / 2, 2)
        suggested_mod  = round((min(mod_scores)  + max(none_scores)) / 2, 2)
        print(
            f"\n  Suggested thresholds (midpoint heuristic):\n"
            f"    HIGH     ≥ {suggested_high}\n"
            f"    MODERATE ≥ {suggested_mod}\n"
            f"    (Set via SIMILARITY_THRESHOLD_HIGH / MODERATE env vars)"
        )

    # Save results
    os.makedirs("examples", exist_ok=True)
    out_path = "examples/similarity_calibration.json"
    output = {
        "model": model_name,
        "thresholds": {
            "high":     settings.SIMILARITY_THRESHOLD_HIGH,
            "moderate": settings.SIMILARITY_THRESHOLD_MODERATE,
            "low":      settings.SIMILARITY_THRESHOLD_LOW,
        },
        "accuracy": f"{correct}/{total}",
        "pairs": results,
    }
    with open(out_path, "w") as fh:
        json.dump(output, fh, indent=2)
    print(f"\n  Results saved to {out_path}")
    print(f"{'=' * 72}\n")


if __name__ == "__main__":
    main()
